// File generated by FlutterFire CLI.
// Configured for Firebase project: mob-flutter-app-e9d9c

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('DefaultFirebaseOptions not configured for web');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS: return ios;
      case TargetPlatform.macOS: throw UnsupportedError('DefaultFirebaseOptions not configured for macos');
      case TargetPlatform.windows: throw UnsupportedError('DefaultFirebaseOptions not configured for windows');
      case TargetPlatform.linux: throw UnsupportedError('DefaultFirebaseOptions not configured for linux');
      default: throw UnsupportedError('DefaultFirebaseOptions not supported for this platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17UxYX5oQiVZQ3RnbPSNQvoYYFaC6vsk',
    appId: '1:732493995330:android:fb5ed961bbfebb17643cdb',
    messagingSenderId: '732493995330',
    projectId: 'mob-flutter-app-e9d9c',
    storageBucket: 'mob-flutter-app-e9d9c.firebasestorage.app',
  );

  // iOS app not yet registered — register via Firebase Console if needed
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17UxYX5oQiVZQ3RnbPSNQvoYYFaC6vsk',
    appId: '1:732493995330:ios:placeholder',
    messagingSenderId: '732493995330',
    projectId: 'mob-flutter-app-e9d9c',
    storageBucket: 'mob-flutter-app-e9d9c.firebasestorage.app',
    iosBundleId: 'com.example.audioPlayerApp',
  );
}
